{
 "title": "Internet monitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Google RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance=\"google.com\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fast.com",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastcom_download_bytes_second * 8 / 1000000",
     "legendFormat": "Download"
    },
    { "expr": "fastcom_up*8/1000000", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Google Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{instance=\"google.com\", job=\"blackbox-icmp\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}