{
 "title": "ICMP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Google RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance=\"google.com\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Google Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"google.com\", job=\"blackbox-icmp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance=\"one.one.one.one\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{instance=\"one.one.one.one\", job=\"blackbox-icmp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fastly RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\", instance=\"fastly.com\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fastly Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "probe_success{instance=\"one.one.one.one\", job=\"blackbox-icmp\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}