modules:
  icmp:
    prober: icmp
    timeout: 1s
    icmp:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      ttl: 64
  dns:
    prober: dns
    timeout: 1s
    dns:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      query_name: google.com
      query_type: A
